%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.27.4

-ifndef(lasp_pb).
-define(lasp_pb, true).

-define(lasp_pb_gpb_version, "3.27.4").

-ifndef('REQ_PB_H').
-define('REQ_PB_H', true).
-record(req,
        {u                              % oneof
        }).
-endif.

-ifndef('OPGET_PB_H').
-define('OPGET_PB_H', true).
-record(opget,
        {key,                           % = 1, string
         type                           % = 2, string
        }).
-endif.

-ifndef('OPUPDATE_PB_H').
-define('OPUPDATE_PB_H', true).
-record(opupdate,
        {k,                             % = 1, {msg,opget}
         e,                             % = 2, {msg,entry}
         actor                          % = 3, string
        }).
-endif.

-ifndef('ENTRY_PB_H').
-define('ENTRY_PB_H', true).
-record(entry,
        {u                              % oneof
        }).
-endif.

-ifndef('PAIR_PB_H').
-define('PAIR_PB_H', true).
-record(pair,
        {a,                             % = 1, {msg,entry}
         b                              % = 2, {msg,entry}
        }).
-endif.

-ifndef('TRIPLE_PB_H').
-define('TRIPLE_PB_H', true).
-record(triple,
        {a,                             % = 1, {msg,entry}
         b,                             % = 2, {msg,entry}
         c                              % = 3, {msg,entry}
        }).
-endif.

-ifndef('VALCOUNTER_PB_H').
-define('VALCOUNTER_PB_H', true).
-record(valcounter,
        {val                            % = 1, int64
        }).
-endif.

-ifndef('VALSET_PB_H').
-define('VALSET_PB_H', true).
-record(valset,
        {elems = []                     % = 1, [string]
        }).
-endif.

-ifndef('VALMAP_PB_H').
-define('VALMAP_PB_H', true).
-record(valmap,
        {entries = []                   % = 1, [{msg,mapentry}]
        }).
-endif.

-ifndef('VALREG_PB_H').
-define('VALREG_PB_H', true).
-record(valreg,
        {val                            % = 1, string
        }).
-endif.

-ifndef('MAPENTRY_PB_H').
-define('MAPENTRY_PB_H', true).
-record(mapentry,
        {key,                           % = 1, string
         ktype,                         % = 2, string
         val                            % = 3, {msg,mapfield}
        }).
-endif.

-ifndef('MAPFIELD_PB_H').
-define('MAPFIELD_PB_H', true).
-record(mapfield,
        {v                              % oneof
        }).
-endif.

-endif.
